### ISSUE TITLE
Unnable to stablish connection with client

### ISSUE THREAD

**Issue by bruno-pinheiro** [bruno-pinheiro/aceleradev-data-science#1]
On the [app project created in the introduction](../tree/master/introduction/02-stats-api) I'm getting the following error message when calling the client.py module.

It seems to be  something with requests or urllib3. It's running on Ubuntu 18.10 with conda virtual environment.

```bash
$ python client.py

Traceback (most recent call last):
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/bruno/miniconda3/envs/stats-api/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/bruno/miniconda3/envs/stats-api/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/bruno/miniconda3/envs/stats-api/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/bruno/miniconda3/envs/stats-api/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/bruno/miniconda3/envs/stats-api/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at
0x7f7da457fba8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/bruno/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries
exceeded with url: /data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection
object at 0x7f7da457fba8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 17, in <module>
    main()
  File "client.py", line 13, in main
    send([1, 2, 3, 4])
  File "client.py", line 7, in send
    response = requests.post("http://localhost:5000/data", json={"data": data})
  File "/home/bruno/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/bruno/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bruno/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bruno/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/bruno/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7da457fba8>: Failed to
establish a new connection: [Errno 111] Connection refused',))
```
I'm using Python 3.6 and here is the requirements.txt:

```bash
$ pip freeze

alabaster==0.7.12
ansimarkup==1.4.0
asn1crypto==0.24.0
astroid==2.2.5
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
better-exceptions-fork==0.2.1.post6
bleach==3.1.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
cloudpickle==0.8.1
colorama==0.4.1
cryptography==2.6.1
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
docutils==0.14
entrypoints==0.3
Flask==1.0.3
idna==2.8
imagesize==1.1.0
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
isort==4.3.16
itsdangerous==1.1.0
jedi==0.13.3
jeepney==0.4
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.6
jupyterlab-server==0.2.0
keyring==19.0.1
kiwisolver==1.1.0
lazy-object-proxy==1.3.1
loguru==0.2.5
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
mistune==0.8.4
nbconvert==5.5.0
nbformat==4.4.0
notebook==5.7.8
numpy==1.16.4
numpydoc==0.8.0
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
prometheus-client==0.6.0
prompt-toolkit==2.0.9
psutil==5.6.1
ptyprocess==0.6.0
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.4.0
PyQt5==5.12
PyQt5-sip==4.19.15
pyrsistent==0.15.2
PySocks==1.7.0
python-dateutil==2.8.0
pytz==2019.1
pyzmq==18.0.1
QtAwesome==0.5.7
qtconsole==4.4.3
QtPy==1.7.0
requests==2.21.0
rope==0.14.0
SecretStorage==3.1.1
Send2Trash==1.5.0
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.8.5
sphinxcontrib-websupport==1.1.0
spyder==3.3.3
spyder-kernels==0.4.2
terminado==0.8.2
testpath==0.4.2
tornado==6.0.2
traitlets==4.3.2
typed-ast==1.3.1
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
wrapt==1.11.1
wurlitzer==1.0.2
```

**Comment by sththiago** [comment]
Hey, Bruno! 

I check your code. First, I check your code and on [this file](https://github.com/bruno-pinheiro/aceleradev-data-science/blob/master/introduction/02-stats-api/statsapi/data_store.py) you have a little error, I think you write `:` in place of `=`. But this don't have that much connection with the error. Fixing this, I couldn't reproduce the error. Can you check if the code that you got the error and the code on repo are the same?

**Comment by bruno-pinheiro** [comment]
Hi Thiago! Many thanks for your time. I had fixed the code error you found on [data_store.py](../introduction/02-stats-api/statsapi/data_store.py), but is still not working. It's weird because when a run the file [app.py](../introduction/02-stats-api/app.py) it runs, but not when I call the client. I'm still stucked on this.

**Comment by bruno-pinheiro** [comment]
I have reinstalled everything, from the OS to the virtual environment. Now I'm running on Ubuntu 18.04, and have a conda environment with this requirements.txt.

```bash
$ pip freeze

ansimarkup==1.4.0
asn1crypto==0.24.0
better-exceptions-fork==0.2.1.post6
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
Click==7.0
colorama==0.4.1
cryptography==2.7
Flask==1.0.3
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
loguru==0.2.5
MarkupSafe==1.1.1
pycparser==2.19
Pygments==2.4.2
pyOpenSSL==19.0.0
PySocks==1.7.0
requests==2.22.0
six==1.12.0
urllib3==1.24.2
Werkzeug==0.15.4
```
But, I'm still getting the same error.
